metadata:
  namespace: commons
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: commons-key
      containers:
        - volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: DATASTORE_NAMESPACE
              valueFrom:
               configMapKeyRef:
                  name: ${project.artifactId}
                  key: datastore.namespace
            - name: DATASTORE_KIND
              valueFrom:
               configMapKeyRef:
                  name: ${project.artifactId}
                  key: datastore.kind
            - name: PUBSUB_SUBSNAME
              valueFrom:
               configMapKeyRef:
                  name: ${project.artifactId}
                  key: pubsub.subsname
            - name: PUBSUB_TOPIC
              valueFrom:
               configMapKeyRef:
                  name: ${project.artifactId}
                  key: pubsub.topic
          imagePullPolicy: Always
