server:
    port: '${PORT:8080}'
    servlet:
        contextPath: /api/v1
datastore:
    namespace: '${DATASTORE_NAMESPACE:apix2018}'
    kind: '${DATASTORE_KIND:solicitacoes}'
pubsub:
    topic: '${PUBSUB_TOPIC:pagamentos-out}'
    subsname: '${PUBSUB_SUBSCRIPTION:pagamentos-in}'
